import { Permission, PERMISSIONS } from "@judgehub/schemas";

export interface BuiltinRoleDefinition {
  key: string;
  name: string;
  description: string;
  permissions: Permission[];
}

export const BUILTIN_ROLES: Record<string, BuiltinRoleDefinition> = {
  super_admin: {
    key: "super_admin",
    name: "Platform Super Admin",
    description: "Full access across entire platform",
    permissions: [...PERMISSIONS],
  },
  org_admin: {
    key: "org_admin",
    name: "Organization Owner/Admin",
    description: "Manage organization, events, members and templates",
    permissions: [
      "org:read",
      "org:update",
      "org:manage_members",
      "event:create",
      "event:read",
      "event:update",
      "event:delete",
      "event:configure",
      "event:publish",
      "entry:create",
      "entry:read",
      "entry:update",
      "entry:delete",
      "entry:disqualify",
      "judge:invite",
      "judge:manage",
      "judge:assign",
      "evaluation:read_all",
      "evaluation:unlock",
      "results:compute",
      "results:view_draft",
      "results:finalize",
      "results:publish",
      "audit:read",
    ],
  },
  event_organizer: {
    key: "event_organizer",
    name: "Event Organizer",
    description: "Full event configuration, entries, judges, assignments and publishing",
    permissions: [
      "event:read",
      "event:update",
      "event:configure",
      "event:publish",
      "entry:create",
      "entry:read",
      "entry:update",
      "entry:delete",
      "entry:disqualify",
      "judge:invite",
      "judge:manage",
      "judge:assign",
      "evaluation:read_all",
      "evaluation:unlock",
      "results:compute",
      "results:view_draft",
      "results:finalize",
      "results:publish",
      "audit:read",
    ],
  },
  head_judge: {
    key: "head_judge",
    name: "Head Judge / Panel Chair",
    description: "Judges entries, resolves ties, unlocks scores, views draft progress",
    permissions: [
      "event:read",
      "entry:read",
      "evaluation:create",
      "evaluation:read_own",
      "evaluation:read_all",
      "evaluation:submit",
      "evaluation:unlock",
      "results:compute",
      "results:view_draft",
    ],
  },
  judge: {
    key: "judge",
    name: "Judge",
    description: "Scores assigned entries and views own history",
    permissions: [
      "event:read",
      "entry:read",
      "evaluation:create",
      "evaluation:read_own",
      "evaluation:submit",
    ],
  },
  scorekeeper: {
    key: "scorekeeper",
    name: "Scorekeeper / Coordinator",
    description: "Enters paper evaluations on behalf of judges and checks in entries",
    permissions: [
      "event:read",
      "entry:read",
      "evaluation:create",
      "evaluation:read_all",
      "evaluation:submit",
    ],
  },
  participant: {
    key: "participant",
    name: "Participant / Team Lead",
    description: "Submits and edits own entry until deadline",
    permissions: [
      "event:read",
      "entry:create",
      "entry:read",
      "entry:update",
    ],
  },
  auditor: {
    key: "auditor",
    name: "Auditor / Observer",
    description: "Read-only access to audit trail and calculations",
    permissions: [
      "event:read",
      "entry:read",
      "evaluation:read_all",
      "results:view_draft",
      "audit:read",
    ],
  },
  public: {
    key: "public",
    name: "Public / Audience",
    description: "Read-only public leaderboard and audience interaction",
    permissions: [
      "event:read",
    ],
  },
};
